secret: xyLG85ePV8Zf15t8YcTv4kID
client_url:
    test.tarejtabeneficios.gointegro.com:
        url:    "test.tarejtabeneficios.gointegro.com"
        path_image_card_front: "http://test.tarejtabeneficios.gointegro.com/images/test.jpg"
        path_image_card_back: "http://test.tarejtabeneficios.gointegro.com/images/test.jpg"
    test2.tarejtabeneficios.gointegro.com:
        url:   "test2.tarejtabeneficios.gointegro.com"
        path_image_card_front:    "http://test.tarejtabeneficios.gointegro.com/images/test2.jpg"
        path_image_card_back: "http://test.tarejtabeneficios.gointegro.com/images/test2.jpg"
    boavista.tarejtabeneficios.gointegro.com:
        url:   "boavista.tarejtabeneficios.gointegro.com"
        path_image_card_front:    "http://boavista.tarejtabeneficios.gointegro.com/images/boavista_f.jpg"
        path_image_card_back: "http://boavista.tarejtabeneficios.gointegro.com/images/boavista_b.jpg"
    incompany.tarejtabeneficios.gointegro.com:
        url:   "incompany.tarejtabeneficios.gointegro.com"
        path_image_card_front:    "http://incompany.tarejtabeneficios.gointegro.com/images/incompany_f.jpg"
        path_image_card_back: "http://incompany.tarejtabeneficios.gointegro.com/images/incompany_b.jpg"
	kc.tarejtabeneficios.gointegro.com:
        url:   "kc.tarejtabeneficios.gointegro.com"
        path_image_card_front:    "http://kc.tarejtabeneficios.gointegro.com/images/kc_f.jpg"
        path_image_card_back: "http://kc.tarejtabeneficios.gointegro.com/images/kc_b.jpg"
	pepsico.tarejtabeneficios.gointegro.com:
        url:   "pepsico.tarejtabeneficios.gointegro.com"
        path_image_card_front:    "http://pepsico.tarejtabeneficios.gointegro.com/images/pepsico_f.jpg"
        path_image_card_back: "http://pepsico.tarejtabeneficios.gointegro.com/images/pepsico_b.jpg"
	sanofi.tarejtabeneficios.gointegro.com:
        url:   "sanofi.tarejtabeneficios.gointegro.com"
        path_image_card_front:    "http://sanofi.tarejtabeneficios.gointegro.com/images/sanofi_f.jpg"
        path_image_card_back: "http://sanofi.tarejtabeneficios.gointegro.com/images/sanofi_b.jpg"
